export interface stockReqData {
    RSYM: string,
    SYMB: string,
    ZDIV: string,
    TYMD: string,
    XYMD: string,
    XHMS: string,
    KYMD: string,
    KHMS: string,
    OPEN: string,
    HIGH: string,
    LOW: string,
    LAST: string,
    SIGN: string,
    DIFF: string,
    RATE: string,
    PBID: string,
    PASK: string,
    VBID: string,
    VASK: string,
    EVOL: string,
    TVOL: string,
    TAMT: string,
    BIVL: string,
    ASVL: string,
    STRN: string,
    MTYP: string
}
