
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
export const prismaVersion: PrismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  EtfList: 'EtfList',
  EtfPriceHistory: 'EtfPriceHistory',
  EtfStockList: 'EtfStockList',
  StockList: 'StockList',
  StockPriceHistory: 'StockPriceHistory',
  Token: 'Token',
  rate: 'rate'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "etfList" | "etfPriceHistory" | "etfStockList" | "stockList" | "stockPriceHistory" | "token" | "rate"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    EtfList: {
      payload: Prisma.$EtfListPayload<ExtArgs>
      fields: Prisma.EtfListFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EtfListFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EtfListFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>
        }
        findFirst: {
          args: Prisma.EtfListFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EtfListFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>
        }
        findMany: {
          args: Prisma.EtfListFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>[]
        }
        create: {
          args: Prisma.EtfListCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>
        }
        createMany: {
          args: Prisma.EtfListCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.EtfListDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>
        }
        update: {
          args: Prisma.EtfListUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>
        }
        deleteMany: {
          args: Prisma.EtfListDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EtfListUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.EtfListUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfListPayload>
        }
        aggregate: {
          args: Prisma.EtfListAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEtfList>
        }
        groupBy: {
          args: Prisma.EtfListGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EtfListGroupByOutputType>[]
        }
        count: {
          args: Prisma.EtfListCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EtfListCountAggregateOutputType> | number
        }
      }
    }
    EtfPriceHistory: {
      payload: Prisma.$EtfPriceHistoryPayload<ExtArgs>
      fields: Prisma.EtfPriceHistoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EtfPriceHistoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EtfPriceHistoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>
        }
        findFirst: {
          args: Prisma.EtfPriceHistoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EtfPriceHistoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>
        }
        findMany: {
          args: Prisma.EtfPriceHistoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>[]
        }
        create: {
          args: Prisma.EtfPriceHistoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>
        }
        createMany: {
          args: Prisma.EtfPriceHistoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.EtfPriceHistoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>
        }
        update: {
          args: Prisma.EtfPriceHistoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>
        }
        deleteMany: {
          args: Prisma.EtfPriceHistoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EtfPriceHistoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.EtfPriceHistoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfPriceHistoryPayload>
        }
        aggregate: {
          args: Prisma.EtfPriceHistoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEtfPriceHistory>
        }
        groupBy: {
          args: Prisma.EtfPriceHistoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EtfPriceHistoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.EtfPriceHistoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EtfPriceHistoryCountAggregateOutputType> | number
        }
      }
    }
    EtfStockList: {
      payload: Prisma.$EtfStockListPayload<ExtArgs>
      fields: Prisma.EtfStockListFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EtfStockListFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EtfStockListFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>
        }
        findFirst: {
          args: Prisma.EtfStockListFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EtfStockListFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>
        }
        findMany: {
          args: Prisma.EtfStockListFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>[]
        }
        create: {
          args: Prisma.EtfStockListCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>
        }
        createMany: {
          args: Prisma.EtfStockListCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.EtfStockListDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>
        }
        update: {
          args: Prisma.EtfStockListUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>
        }
        deleteMany: {
          args: Prisma.EtfStockListDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EtfStockListUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.EtfStockListUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EtfStockListPayload>
        }
        aggregate: {
          args: Prisma.EtfStockListAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEtfStockList>
        }
        groupBy: {
          args: Prisma.EtfStockListGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EtfStockListGroupByOutputType>[]
        }
        count: {
          args: Prisma.EtfStockListCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EtfStockListCountAggregateOutputType> | number
        }
      }
    }
    StockList: {
      payload: Prisma.$StockListPayload<ExtArgs>
      fields: Prisma.StockListFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StockListFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StockListFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>
        }
        findFirst: {
          args: Prisma.StockListFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StockListFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>
        }
        findMany: {
          args: Prisma.StockListFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>[]
        }
        create: {
          args: Prisma.StockListCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>
        }
        createMany: {
          args: Prisma.StockListCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.StockListDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>
        }
        update: {
          args: Prisma.StockListUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>
        }
        deleteMany: {
          args: Prisma.StockListDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StockListUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.StockListUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockListPayload>
        }
        aggregate: {
          args: Prisma.StockListAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStockList>
        }
        groupBy: {
          args: Prisma.StockListGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StockListGroupByOutputType>[]
        }
        count: {
          args: Prisma.StockListCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StockListCountAggregateOutputType> | number
        }
      }
    }
    StockPriceHistory: {
      payload: Prisma.$StockPriceHistoryPayload<ExtArgs>
      fields: Prisma.StockPriceHistoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StockPriceHistoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StockPriceHistoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>
        }
        findFirst: {
          args: Prisma.StockPriceHistoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StockPriceHistoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>
        }
        findMany: {
          args: Prisma.StockPriceHistoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>[]
        }
        create: {
          args: Prisma.StockPriceHistoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>
        }
        createMany: {
          args: Prisma.StockPriceHistoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.StockPriceHistoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>
        }
        update: {
          args: Prisma.StockPriceHistoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>
        }
        deleteMany: {
          args: Prisma.StockPriceHistoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StockPriceHistoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.StockPriceHistoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StockPriceHistoryPayload>
        }
        aggregate: {
          args: Prisma.StockPriceHistoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStockPriceHistory>
        }
        groupBy: {
          args: Prisma.StockPriceHistoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StockPriceHistoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.StockPriceHistoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StockPriceHistoryCountAggregateOutputType> | number
        }
      }
    }
    Token: {
      payload: Prisma.$TokenPayload<ExtArgs>
      fields: Prisma.TokenFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TokenFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TokenFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>
        }
        findFirst: {
          args: Prisma.TokenFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TokenFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>
        }
        findMany: {
          args: Prisma.TokenFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>[]
        }
        create: {
          args: Prisma.TokenCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>
        }
        createMany: {
          args: Prisma.TokenCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.TokenDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>
        }
        update: {
          args: Prisma.TokenUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>
        }
        deleteMany: {
          args: Prisma.TokenDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TokenUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.TokenUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokenPayload>
        }
        aggregate: {
          args: Prisma.TokenAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateToken>
        }
        groupBy: {
          args: Prisma.TokenGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TokenGroupByOutputType>[]
        }
        count: {
          args: Prisma.TokenCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TokenCountAggregateOutputType> | number
        }
      }
    }
    rate: {
      payload: Prisma.$ratePayload<ExtArgs>
      fields: Prisma.rateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.rateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.rateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>
        }
        findFirst: {
          args: Prisma.rateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.rateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>
        }
        findMany: {
          args: Prisma.rateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>[]
        }
        create: {
          args: Prisma.rateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>
        }
        createMany: {
          args: Prisma.rateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.rateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>
        }
        update: {
          args: Prisma.rateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>
        }
        deleteMany: {
          args: Prisma.rateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.rateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.rateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ratePayload>
        }
        aggregate: {
          args: Prisma.RateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRate>
        }
        groupBy: {
          args: Prisma.rateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RateGroupByOutputType>[]
        }
        count: {
          args: Prisma.rateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RateCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const EtfListScalarFieldEnum = {
  market: 'market',
  stockCode: 'stockCode',
  etfName: 'etfName',
  companyName: 'companyName',
  benchmarkIndex: 'benchmarkIndex',
  indexComment: 'indexComment',
  tradingLot: 'tradingLot',
  trustFeeRate: 'trustFeeRate',
  stdPdno: 'stdPdno',
  isin_code: 'isin_code',
  regDate: 'regDate',
  modDate: 'modDate'
} as const

export type EtfListScalarFieldEnum = (typeof EtfListScalarFieldEnum)[keyof typeof EtfListScalarFieldEnum]


export const EtfPriceHistoryScalarFieldEnum = {
  priceIdx: 'priceIdx',
  market: 'market',
  stockCode: 'stockCode',
  open: 'open',
  high: 'high',
  low: 'low',
  price: 'price',
  lastDayPrice: 'lastDayPrice',
  h52p: 'h52p',
  l52p: 'l52p',
  tXprc: 'tXprc',
  tXdif: 'tXdif',
  tXrat: 'tXrat',
  tRate: 'tRate',
  regDate: 'regDate'
} as const

export type EtfPriceHistoryScalarFieldEnum = (typeof EtfPriceHistoryScalarFieldEnum)[keyof typeof EtfPriceHistoryScalarFieldEnum]


export const EtfStockListScalarFieldEnum = {
  market: 'market',
  etfStockCode: 'etfStockCode',
  stockCode: 'stockCode',
  checkDate: 'checkDate',
  etfPercent: 'etfPercent'
} as const

export type EtfStockListScalarFieldEnum = (typeof EtfStockListScalarFieldEnum)[keyof typeof EtfStockListScalarFieldEnum]


export const StockListScalarFieldEnum = {
  market: 'market',
  stockCode: 'stockCode',
  stockName: 'stockName',
  trCrcyCd: 'trCrcyCd',
  buyUnitQty: 'buyUnitQty',
  prdtName: 'prdtName',
  stockComment: 'stockComment',
  stdPdno: 'stdPdno',
  isin_code: 'isin_code',
  regDate: 'regDate',
  modDate: 'modDate'
} as const

export type StockListScalarFieldEnum = (typeof StockListScalarFieldEnum)[keyof typeof StockListScalarFieldEnum]


export const StockPriceHistoryScalarFieldEnum = {
  priceIdx: 'priceIdx',
  market: 'market',
  stockCode: 'stockCode',
  open: 'open',
  high: 'high',
  low: 'low',
  price: 'price',
  lastDayPrice: 'lastDayPrice',
  tomv: 'tomv',
  h52p: 'h52p',
  l52p: 'l52p',
  perx: 'perx',
  pbrx: 'pbrx',
  epsx: 'epsx',
  bpsx: 'bpsx',
  tXprc: 'tXprc',
  tXdif: 'tXdif',
  tXrat: 'tXrat',
  tRate: 'tRate',
  eIcod: 'eIcod',
  regDate: 'regDate'
} as const

export type StockPriceHistoryScalarFieldEnum = (typeof StockPriceHistoryScalarFieldEnum)[keyof typeof StockPriceHistoryScalarFieldEnum]


export const TokenScalarFieldEnum = {
  tokenIdx: 'tokenIdx',
  regDate: 'regDate',
  token: 'token'
} as const

export type TokenScalarFieldEnum = (typeof TokenScalarFieldEnum)[keyof typeof TokenScalarFieldEnum]


export const RateScalarFieldEnum = {
  rate_idx: 'rate_idx',
  reg_date: 'reg_date',
  usd_rate: 'usd_rate',
  jpy_rate: 'jpy_rate',
  eur_rate: 'eur_rate',
  sgd_rate: 'sgd_rate'
} as const

export type RateScalarFieldEnum = (typeof RateScalarFieldEnum)[keyof typeof RateScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const EtfListOrderByRelevanceFieldEnum = {
  market: 'market',
  stockCode: 'stockCode',
  etfName: 'etfName',
  companyName: 'companyName',
  benchmarkIndex: 'benchmarkIndex',
  indexComment: 'indexComment',
  tradingLot: 'tradingLot',
  trustFeeRate: 'trustFeeRate',
  stdPdno: 'stdPdno',
  isin_code: 'isin_code'
} as const

export type EtfListOrderByRelevanceFieldEnum = (typeof EtfListOrderByRelevanceFieldEnum)[keyof typeof EtfListOrderByRelevanceFieldEnum]


export const EtfPriceHistoryOrderByRelevanceFieldEnum = {
  market: 'market',
  stockCode: 'stockCode',
  open: 'open',
  high: 'high',
  low: 'low',
  price: 'price',
  lastDayPrice: 'lastDayPrice',
  h52p: 'h52p',
  l52p: 'l52p',
  tXprc: 'tXprc',
  tXdif: 'tXdif',
  tXrat: 'tXrat',
  tRate: 'tRate'
} as const

export type EtfPriceHistoryOrderByRelevanceFieldEnum = (typeof EtfPriceHistoryOrderByRelevanceFieldEnum)[keyof typeof EtfPriceHistoryOrderByRelevanceFieldEnum]


export const EtfStockListOrderByRelevanceFieldEnum = {
  market: 'market',
  etfStockCode: 'etfStockCode',
  stockCode: 'stockCode'
} as const

export type EtfStockListOrderByRelevanceFieldEnum = (typeof EtfStockListOrderByRelevanceFieldEnum)[keyof typeof EtfStockListOrderByRelevanceFieldEnum]


export const StockListOrderByRelevanceFieldEnum = {
  market: 'market',
  stockCode: 'stockCode',
  stockName: 'stockName',
  trCrcyCd: 'trCrcyCd',
  buyUnitQty: 'buyUnitQty',
  prdtName: 'prdtName',
  stockComment: 'stockComment',
  stdPdno: 'stdPdno',
  isin_code: 'isin_code'
} as const

export type StockListOrderByRelevanceFieldEnum = (typeof StockListOrderByRelevanceFieldEnum)[keyof typeof StockListOrderByRelevanceFieldEnum]


export const StockPriceHistoryOrderByRelevanceFieldEnum = {
  market: 'market',
  stockCode: 'stockCode',
  open: 'open',
  high: 'high',
  low: 'low',
  price: 'price',
  lastDayPrice: 'lastDayPrice',
  tomv: 'tomv',
  h52p: 'h52p',
  l52p: 'l52p',
  perx: 'perx',
  pbrx: 'pbrx',
  epsx: 'epsx',
  bpsx: 'bpsx',
  tXprc: 'tXprc',
  tXdif: 'tXdif',
  tXrat: 'tXrat',
  tRate: 'tRate',
  eIcod: 'eIcod'
} as const

export type StockPriceHistoryOrderByRelevanceFieldEnum = (typeof StockPriceHistoryOrderByRelevanceFieldEnum)[keyof typeof StockPriceHistoryOrderByRelevanceFieldEnum]


export const TokenOrderByRelevanceFieldEnum = {
  regDate: 'regDate',
  token: 'token'
} as const

export type TokenOrderByRelevanceFieldEnum = (typeof TokenOrderByRelevanceFieldEnum)[keyof typeof TokenOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  etfList?: Prisma.EtfListOmit
  etfPriceHistory?: Prisma.EtfPriceHistoryOmit
  etfStockList?: Prisma.EtfStockListOmit
  stockList?: Prisma.StockListOmit
  stockPriceHistory?: Prisma.StockPriceHistoryOmit
  token?: Prisma.TokenOmit
  rate?: Prisma.rateOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

